### ISSUE TITLE
depoyu guncelleyin komutunu kendiniz bir kere denediniz mi? 

### ISSUE THREAD

**Issue by kunthar** [zetaops/ulakbus.org#6]
Bu belgedeki
http://www.ulakbus.org/wiki/development_environment_setup.html

```
sudo su - ulakbus
cd ulakbus
git pull https://github.com/zetaops/ulakbus.git
```

komutunun sonucu asagidaki gibi oluyor. 

```
ulakbus@ulakbus:~/ulakbus$ git pull https://github.com/zetaops/ulakbus.git
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
From https://github.com/zetaops/ulakbus
 * branch            HEAD       -> FETCH_HEAD

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'ulakbus@ulakbus.(none)')
```

ne yapmamiz gerekiyor simdi?

**Comment by alirizakeles** [comment]
Iki sebebi olabilir:
- Basitce git config ayarlarinizi dogru yapmamis olabilirsiniz. Kendi forkunuzda calisiyorsaniz remote depolarin dogru ayarlandigindan emin olun. Temel git belgeleri yardimci olabilir:
  https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup#Your-Identity
- Eger local git deponuzun kullanicisi vmdeki kullanici degilse, host makinesindeki local depolari paylastirilmis dizinler seklinde sanal makineye bagladiysaniz, git islemlerini host makineden yapmaniz gerekir. Git, degiklikleri izleyebilmek icin kim oldugunuzu global veya o depoya ozel ayarlardan bilmek durumunda. Eger bu ayarlari local olarak yaparsaniz vm icinden de git islemlerini yapabilirsiniz. Yukaridaki baglanti git ayarlarinizi nasil yapacaginizi anlatmaktadir.

Ayrica uzak depoya erisim icin kullandiginiz ssh anahtarlari icin de benzer durum gecerlidir. VM icinden bu erisimi saglamak isterseniz tipki host makinesinde yaptiginiz gibi ssh anahtarlari uretip remote depoya eklemeniz gerekmektedir. Ya da mevcut public/private keylerinizi vm icine koymaniz gerekir. Gecici bir key olursutmanizi oneririz. Github icin suraya bakabilirsiniz: https://help.github.com/articles/generating-ssh-keys/

**Comment by kunthar** [comment]
sizin sagladiginiz vagrant vm icinde oluyor bunlar. o zaman acik bir dille
bu ayarlarin nasil yapilacagini anlatmaniz gerekiyor. daha yeni
indirdigimiz bir vm uzerinde ne yapacagimizi birinin anlatmasi lazimdir.
