### ISSUE TITLE
vagrant file duzenlenmesi

### ISSUE THREAD

**Issue by kunthar** [zetaops/ulakbus.org#8]
mevcut vagrant file icinde portlar ve diger ayarlar son durumda degil. guncellenmesi gerekiyor.

**Comment by alirizakeles** [comment]
Ornek vagrant file surada yazilmis zaten:
https://github.com/zetaops/ulakbus-development-box/blob/master/Vagrantfile.sample

Buna isaret edip belgeyi guncelliyorum.

**Comment by alirizakeles** [comment]
https://github.com/zetaops/ulakbus.org/commit/bae12558724592e08bd3126836c11ef30a570597
